name: "ContinuousTesting"

on:
  push:
  pull_request:

jobs:
  perform-api-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment: env_compose

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build Certificates
        run: |
          mkdir Konfiguration/"TLS Zertifikate"
          cd Konfiguration/"TLS Zertifikate"/
          echo "${{ secrets.AUTHENTICATION_DB_CERT }}" >> authentication-db-cert.pem
          echo "${{ secrets.AUTHENTICATION_DB_KEY }}" >> authentication-db-key.pem
          echo "${{ secrets.AUTHENTICATION_SERVICE_HTTPS_CERT }}" >> authentication-service-https-cert.pem
          echo "${{ secrets.AUTHENTICATION_SERVICE_HTTPS_KEY }}" >> authentication-service-https-key.pem
          echo "${{ secrets.BFF_HTTPS_CERT }}" >> bff-https-cert.pem
          echo "${{ secrets.BFF_HTTPS_KEY }}" >> bff-https-key.pem
          echo "${{ secrets.CA_CERT }}" >> ca-cert.pem
          echo "${{ secrets.FILE_DB_CERT }}" >> file-db-cert.pem
          echo "${{ secrets.FILE_DB_KEY }}" >> file-db-key.pem
          echo "${{ secrets.FILE_SERVICE_HTTPS_CERT }}" >> file-service-https-cert.pem
          echo "${{ secrets.FILE_SERVICE_HTTPS_KEY }}" >> file-service-https-key.pem
          mkdir ../"Signature Key Pair"/
          cd ../"Signature Key Pair"/
          echo "${{ secrets.JWT_SIGNATURE_RSA_PRIVATE }}" >> jwt-signature-rsa-private.pem
          echo "${{ secrets.JWT_SIGNATURE_RSA_PUBLIC }}" >> jwt-signature-rsa-public.pem

      - name: Build Container Images
        run: |
          chmod 700 ./build_docker_images.sh
          ./build_docker_images.sh

      - name: Start Containers
        run: docker compose up -d
        env:
          AUTH_SERVICE_POSTGRES_DATABASE: ${{ secrets.AUTH_SERVICE_POSTGRES_DATABASE }}
          AUTH_SERVICE_POSTGRES_USERNAME: ${{ secrets.AUTH_SERVICE_POSTGRES_USERNAME }}
          AUTH_SERVICE_POSTGRES_PASSWORD: ${{ secrets.AUTH_SERVICE_POSTGRES_PASSWORD }}
          AUTH_SERVICE_GOOGLE_CLIENT_ID: ${{ secrets.AUTH_SERVICE_GOOGLE_CLIENT_ID }}
          AUTH_SERVICE_SOCIAL_SECRET: ${{ secrets.AUTH_SERVICE_SOCIAL_SECRET }}
          AUTH_SERVICE_EMAIL_HOST_USER: ${{ secrets.AUTH_SERVICE_EMAIL_HOST_USER }}
          AUTH_SERVICE_EMAIL_HOST_PASSWORD: ${{ secrets.AUTH_SERVICE_EMAIL_HOST_PASSWORD }}
          AUTH_SERVICE_ACCESS_TOKEN_LIFETIME: ${{ secrets.AUTH_SERVICE_ACCESS_TOKEN_LIFETIME }}
          AUTH_SERVICE_FRONTEND_REDIRECT_URI:  ${{ secrets.AUTH_SERVICE_FRONTEND_REDIRECT_URI }}
          AUTH_SERVICE_ROOT_URI:  ${{ secrets.AUTH_SERVICE_ROOT_URI }}
          FILE_SERVICE_POSTGRES_DATABASE: ${{ secrets.FILE_SERVICE_POSTGRES_DATABASE }}
          FILE_SERVICE_POSTGRES_USERNAME: ${{ secrets.FILE_SERVICE_POSTGRES_USERNAME }}
          FILE_SERVICE_POSTGRES_PASSWORD: ${{ secrets.FILE_SERVICE_POSTGRES_PASSWORD }}
          DJANGO_SECRET: ${{ secrets.DJANGO_SECRET }}
          USER_UPDATE_QUEUE_USERNAME: ${{ secrets.USER_UPDATE_QUEUE_USERNAME }}
          USER_UPDATE_QUEUE_PASSWORD: ${{ secrets.USER_UPDATE_QUEUE_PASSWORD }}
          USER_UPDATE_QUEUE_EXCHANGE_NAME: ${{ secrets.USER_UPDATE_QUEUE_EXCHANGE_NAME }}

      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash

      - name: Test File API
        if: always()
        run: |
          docker cp ./Dateiverwaltungsdienst/app_file/test patientenakte-file-api:/code/app_file/test/
          docker cp ./Dateiverwaltungsdienst/app_file/fixtures patientenakte-file-api:/code/app_file/fixtures/
          docker exec patientenakte-file-api python manage.py test

      - name: Test Auth API
        if: always()
        run: |
          docker cp ./Authentifizierungsdienst/authentication/test patientenakte-auth-api:/code/authentication/test/
          docker cp ./Authentifizierungsdienst/authentication/fixtures patientenakte-auth-api:/code/authentication/fixtures/
          docker exec patientenakte-auth-api python manage.py test

      - name: Stop containers
        if: always()
        run: docker compose down

  perform-codeql-analysis:
    uses: DavidFambach/SbD-5-TINF20CS1/.github/workflows/codeql.yml@master