services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  auth_api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=AuthService.settings
      - GOOGLE_CLIENT_ID=321799647155-2fn0mq2kubk5tba1g4pu5vo0hjb8vtv4.apps.googleusercontent.com
      - SOCIAL_SECRET=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
      - SECRET_KEY=@6p-h7#oy4unyb4+(@i&3eq(knbkvjkeyv&@*8+a%f45b@mfm1
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db